ruby2js 4.1.1+ causes syntax error
Events.broadcast(function(, ) {
                                        ^
SyntaxError: Unexpected token ','
    at new Script (vm.js:88:7)