Fix error seen in error logs:
App 13229 output: _ERROR #<NoMethodError: undefined method `members' for #<ASF::Committee:0x000000007fe1a8>>
App 13229 output: _WARN /x1/srv/whimsy/www/roster/views/actions/authgroup.json.rb:36:in `_evaluate'
App 13229 output: _WARN /x1/srv/whimsy/www/roster/main.rb:248:in `block in <top (required)>'